#!/bin/bash

set -euo pipefail

################################################################################
# Simple podman wrapper that maps user and mounts PWD

function name {
    local image nametag tag

    image="${1}"

    nametag="${image##*/}"
    name="${nametag%%:*}"
    tag="${nametag##*:}"

    case "${tag}" in
        latest) echo "pet-${name}"        ;;
        *)      echo "pet-${name}-${tag}" ;;
    esac | tr -dc '\-[:alnum:]'
}

function exists {
    local image

    image="${1}"

    podman container exists "$(name "${image}")"
}

function cmd {
    local image

    image="${1}"

    podman image inspect "${image}" | jq -r '.[].Config.Cmd[]'
}

function running {
    local image name

    image="${1}"
    name="$(name "${image}")"

    exists "${image}"
    test "$(podman inspect -f '{{.State.Status}}' "${name}" 2>&1)" = "running"
}

function run {
    local image user name

    image="${1}"
    user="${2:-}"
    name="$(name "${image}")"

    podman run                                                                 \
           ${user:+--user=${user}}                                             \
           --userns   "keep-id"                                                \
           --volume   "${PWD}:/host/${PWD#/}"                                  \
           --workdir  "/host/${PWD#/}"                                         \
           --name     "${name}"                                                \
           --hostname "${name#pet-}"                                           \
           --interactive                                                       \
           --tty                                                               \
           "${image}"
}

function start {
    local image user name cmd

    image="${1}"
    user="${2:-}"
    name="$(name "${image}")"
    cmd="$(cmd "${image}")"

    podman container start "${name}" | { grep -v "${name}" ||: ; }
    podman container exec -it ${user:+--user ${user}} "${name}" "${cmd}"
}

function stop {
    local image user name

    image="${1}"
    name="$(name "${image}")"

    podman container rm --force -t 1 "${name}" | { grep -v "${name}" ||: ; }
}

################################################################################


function usage {
    cat <<EOM
Usage: $(basename "${0}") [-h | --help] <IMAGE> <FLAGS>

  -h, --help    Show this help message.

Run or exec into a container made from IMAGE.

FLAGS are passed verbatim to either run or exec so
should be a flag that works for both subcommands.

EOM
}

function main {
    local o name opts long
    local image root stop

    name="$(basename "${0}")"
    opts="hrs"
    long="help,root,stop"
    o="$(getopt -o "${opts}" -l "${long}" -n "${name}" -- "${@}")"
    eval set -- "${o}"

    root=false
    stop=false
    while true; do
        case "${1}" in
            -h | --help) usage                                                ;;
            -r | --root) root=true                                            ;;
            -s | --stop) stop=true                                            ;;
            -- ) shift; break                                                 ;;
            * )         break                                                 ;;
        esac
        shift
    done

    image="${1}"
    if [ -z "${image}" ]; then
        usage
        return 2
    fi

    if [ "${stop}" = true ]; then
        echo "Stopping ..."
        stop "${image}"
    elif running "${image}"; then
        echo "Re-attaching ..."
        podman attach "$(name "${image}")"
    elif exists "${image}"; then
        echo "Starting ..."
        start "${image}" ${root:+root}
    else
        run   "${image}" ${root:+root}
    fi
}

main "${@}"; exit
