#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: git fpaste-am [git-am options] <url>"
    exit -1
else
    url="${@: -1}/raw/"
    am_args="${@:1:$(($#-1))}"

    curl "${url}" 2>/dev/null | git am $am_args
fi
