#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: git fpaste-apply [git-apply options] <url>"
    exit -1
else
    url="${@: -1}/raw/"
    apply_args="${@:1:$(($#-1))}"

    curl "${url}" 2>/dev/null | git apply $apply_args
fi
