#!/bin/bash

set -e

function get-account {
    local forge

    forge="${1}"

    case "${forge}" in
        lab|hub) echo "default"  ;;
        *)       echo "${forge}" ;;
    esac
}

function get-cmd {
    local forge

    forge="${1}"

    case "${forge}" in
        lab|gnome|smarteye) echo "lab" ;;
        hub)                echo "hub" ;;
        *)
            echo "Unknown forge!"
            exit 2
            ;;
    esac
}

function get-software {
    local forge

    forge="${1}"
    cmd="$(get-cmd "${forge}")"

    case "${cmd}" in
        lab|hub) echo "git${cmd}" ;;
        bb)      echo "bitbucket" ;;
    esac
}

function get-protocol {
    local forge

    forge="${1}"

    case "${forge}" in
        smarteye) echo "http"  ;;
        *)        echo "https" ;;
    esac
}

function get-host {
    local forge

    forge="${1}"

    case "${forge}" in
        hub)      echo "github.com"       ;;
        lab)      echo "gitlab.com"       ;;
        gnome)    echo "gitlab.gnome.org" ;;
        smarteye) echo "git.smarteye.se"  ;;
        *)
            echo "Unknown forge!"
            exit 2
            ;;
    esac
}

function create-account {
    local forge protocol host account

    forge="${1}"

    host="$(get-host "${forge}")"
    cmd="$(get-cmd "${forge}")"
    software="$(get-software "${forge}")"
    protocol="$(get-protocol "${forge}")"
    account="$(get-account "${forge}")"

    grep -F "[${software} \"${account}\"]" ~/.gitspindle > /dev/null 2>&1 && exit $?

    echo "Add account for ${account}: ${host}"
    echo git "${cmd}" add-account --host="${protocol}://${host}" "${account}"
    git "${cmd}" add-account --host="${protocol}://${host}" "${account}"
}

function get-author {
    local repo
    repo="${1}"

    author=$(dirname "${repo}")
    if [ "${author}" = "." ]; then
        whoami
    else
        echo "${author}"
    fi
}

function clone {
    local forge repo author
    forge="${1}"
    repo="${1}"

    author="$(get-author "${forge}")"
    account="$(get-account "${forge}")"
    cmd="$(get-cmd "${forge}")"

    repo="${author}/$(basename "${2}")"

    forge_path="${HOME}/Code/${host}"

    mkdir -p "${forge_path}/${author}"

    git "${cmd}" clone --account="${account}" "${repo}" "${forge_path}/${repo}"
}

forge="${1}"
repo="${2}"

create-account "${forge}"
clone "${forge}" "${repo}"
