#!/bin/bash


if [ $# -lt 1 ] || [[ "$*" == *-h* ]]; then
    echo "Usage: git clone-here [--recursive] <repo>"
    exit 2
fi

if [ -d .git ]; then
    echo "This is already a git repository."
    exit 3
fi

REPO="${1}"

git ls-remote "${REPO}" > /dev/null          || exit $?
git init                                     || exit $?
git remote add origin "${REPO}"              || exit $?
git fetch origin                             || exit $?
git checkout -b master --track origin/master || exit $?

if [[ "$*" == *--recursive* ]]; then
    git submodule update --init --recursive
fi
