#!/bin/bash

set -e

GIT_GET_BASEDIR=${GIT_GET_BASEDIR:-${HOME}/Code}

function with-extension {
    local url

    url="${1}"
    case "${url}" in
        *.git)
            echo "${url}"
            return
            ;;
        *)
            echo "${url}.git"
            return
            ;;
    esac
}

function get-repo-dir {
    local url

    url="$(with-extension "${1}")"

    case "${url}" in
        http://*|https://*)
            repo="${url##*//}" ;;
        *@*.git)
            repo="${url##*@}"
            repo="${repo/://}"
            ;;
        *)
            echo "Not a proper repository! [${url}]"
            exit 3
    esac
    echo "${GIT_GET_BASEDIR}/${repo%.git}"
}

function clone-repo {
    url="${1}"
    repo="$(get-repo-dir "${url}")"

    if [ -d "${repo}" ]; then
        echo "${repo} already exists!"
        return
    fi

    mkdir -p "${repo}"
    git clone "${url}" "${repo}"
}

if [ $# -lt 1 ]; then
    echo "Usage: git get <url>..."
    exit 2
fi

if [ "${1}" == --show-path ]; then
    get-repo-dir "$(git ls-remote --get-url "${2}")"
else
    clone-repo "$(git ls-remote --get-url "${1}")"
fi
