#!/bin/bash

function autosquash {
    CURR_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
    MERGE_BASE="$(git merge-base "${1}" "${CURR_BRANCH}")"
    EDITOR=true git rebase -i --autosquash "${MERGE_BASE}"
}

case "${1}" in
    autosquash)
        shift
        autosquash "${@}"
        ;;
    *)
        echo "Usage: git wip [command] <flags>"
        exit 2
        ;;
esac
