#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2024, Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>

set -e
set -o pipefail


################################################################################


function error {
    echo "ERROR: ${*}" >/dev/stderr
}

function main {
    local scheme

    scheme="$(gsettings get org.gnome.desktop.interface color-scheme)"

    case "${scheme}" in
        "'default'"|"'prefer-light'") echo light ;;
        "'prefer-dark'")              echo dark  ;;
        *)                            error "Unknown color-scheme: ${scheme}" ;;
    esac
}

main "${@}"; exit
