#!/bin/bash

# Copyright 2026, Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

# Keep the GTK3 Adwaita themes in sync with the desktop color scheme.
# This is a hack and might break your app!

set -e
set -o pipefail

declare -A STYLE=(
    # # Adwaita
    # [dark]="Adwaita-dark"
    # [light]="Adwaita-light"

    # Adw-gtk3
    [dark]="adw-gtk3-dark"
    [light]="adw-gtk3"
)

################################################################################

function set-gtk3-color-scheme {
    local scheme

    scheme="${1}"

    echo "GTK3 => ${scheme^^}"
    gsettings set org.gnome.desktop.interface gtk-theme "'${STYLE[${scheme}]}'"
}

function main {
    while read -r line ; do
        case "${line}" in
            *'prefer-dark'*)  set-gtk3-color-scheme dark                      ;;
            *'prefer-light'*) set-gtk3-color-scheme light                     ;;
            *'default'*)      set-gtk3-color-scheme light                     ;;
            *) continue ;;
        esac
    done < <( dconf watch /org/gnome/desktop/interface/color-scheme )
}

main "${@}"; exit
