#!/bin/bash

# Keep the GTK3 Adwaita themes in sync with the desktop color scheme.
# This is a hack and might break your app!

set -e
set -o pipefail


################################################################################

function set-gtk3-color-scheme {
    local scheme

    scheme="${1}"

    echo "GTK3 => ${scheme^^}"
    gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-${scheme}"
}

function main {
    while read -r line ; do
        case "${line}" in
            *'dark'*)    set-gtk3-color-scheme dark  ;;
            *'default'*) set-gtk3-color-scheme light ;;
            *'light'*)   set-gtk3-color-scheme light ;;
        esac
    done < <( dconf watch /org/gnome/desktop/interface/color-scheme )
}

main "${@}"; exit
