#!/bin/bash

# Copyright 2026, Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail


################################################################################

function error {
    echo "ERROR: ${*}" >/dev/stderr
}

################################################################################

function k8s-logged-in {
    if ! kubectl "${@}" auth whoami &>/dev/null; then
        error "Not logged in!"
        echo
        return 2
    fi
}

function main {
    local resource

    k8s-logged-in "${@}"

    echo
    for resource in cronjobs jobs pods; do
        cat <<-EOM
		${resource^^}

		$(kubectl "${@}" get "${resource}" | pr -to 4)

	EOM
    done
}

main "${@}"; exit
