#!/bin/bash

set -eu
set -o pipefail


################################################################################

# shellcheck disable=SC2329
function debug-comp {
    echo "${FUNCNAME[1]:+${FUNCNAME[1]}: }${*}" \
         >> /tmp/kubectl-namespace.comp.log
}

function usage {
    cat <<EOM
Usage: $(basename "${0}" | tr "-" " ") [-h | --help] [NAMESPACE|-]

  -h, --help    Show this help message.

EOM
}

function logged-in {
    if ! out="$(kubectl auth whoami 2>&1)"; then
        echo "${out}" >&2
        return 2
    fi
}

function get-namespaces {
    local err

    err="error: current-context is not set"

    if [ "$(kubectl config current-context 2>&1)" = "${err}" ]; then
        kubectl context >/dev/null
    fi

    if ! logged-in; then
        return 2
    fi

    kubectl get namespaces --no-headers -o name | xargs -n1 basename
}

function set-namespace {
    local namespace

    namespace="${1}"

    if [ "${namespace}" = "-" ]; then
        namespace=""
    fi
    kubectl config set-context --current --namespace="${namespace}"
}

function do-complete {
    if [ "${#}" -lt 2 ] && logged-in; then
        get-namespaces
    else
        # It's very unclear why ":4" specifically turns off further completions.
        # But it does.
        # See: https://github.com/kubernetes/kubernetes/commit/09bbe37ce6043b0e
        echo :4
    fi
}

function switch-namespace {
    local namespaces

    case "${1:-}" in
        -h | --help) usage                                                    ;;
        "") mapfile -t namespaces < <(get-namespaces); wait $!
            set-namespace "$( printf "%s\n" "${namespaces[@]}"                 \
                            | fzf --ansi --height $(( ${#namespaces[@]} + 2))  \
                            )"
            ;;
        *)  set-namespace "${1}"                                              ;;
    esac
}

function main {
    case "$(basename "${0}")" in
        kubectl_complete-*)   do-complete      "${@}" ;;
        *)                    switch-namespace "${@}" ;;
    esac
}

main "${@}"; exit
