#!/bin/bash

set -eu
set -o pipefail


################################################################################

function main {
    local namespaces namespace context_err

    case "${1:-}" in
        -h | --help)
            echo "Usage: $(basename "${0}" | tr "-" " ") [CONTEXT|-]"
            return
            ;;
        *)  ;;
    esac

    context_err="error: current-context is not set"

    if [ "$(kubectl config current-context 2>&1)" = "${context_err}" ]; then
        kubectl context
    fi

    case "${1:-}" in
        "") mapfile -t namespaces < <(kubectl get namespaces                   \
                                              --no-headers                     \
                                              -o name                          \
                                          | xargs -n1 basename                 \
                                     )
            namespace="$( printf "%s\n" "${namespaces[@]}"                     \
                        | fzf --ansi --height $(( ${#namespaces[@]} + 2))      \
                        )"
            ;;

        -)  namespace=""     ;;

        *)  namespace="${1}" ;;
    esac

    kubectl config set-context --current --namespace="${namespace}"
}

main "${@}"; exit
