#!/bin/bash

set -euo pipefail


################################################################################

function usage {
    cat <<EOM
Run a kubectl command over all contexts.

Usage: $(basename "${0}" | tr "-" " ") [-h | --help] [ARGS]

  -h, --help    Show this help message.

EOM
}

function get-contexts {
    kubectl config get-contexts --no-headers -o name
}

function main {
    local -a contexts

    if [ "${#}" -lt 1 ]; then
        usage
        return 2
    fi

    if [[ " ${*} " == *" --help "* ]] || [[ " ${*} " == *" -h "* ]]; then
        usage
        return
    fi

    mapfile -t contexts < <(get-contexts); wait $!

    echo
    for env in "${contexts[@]}"; do
        echo "${env^^}"
        echo
        kubectl --context="${env}" "${@}" |& pr -to 4
        echo
    done
}

main "${@}"; exit
