#!/bin/bash

# Copyright 2026, Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail


################################################################################

function error {
    echo "ERROR: ${*}" >/dev/stderr
}

################################################################################

function k8s-logged-in {
    if ! kubectl "${@}" auth whoami &>/dev/null; then
        error "Not logged in!"
        echo
        return 2
    fi
}

function main {
    local kind resource empty=

    k8s-logged-in "${@}"

    for kind in cronjobs jobs pods; do
        if ! resource="$(kubectl "${@}" get "${kind}" |& pr -to 4)"; then
            error "Failed to get '${kind}'!"
        fi

        case "${resource}" in
            *'No resources found in'*|'') continue                            ;;
            *)                                                                ;;
        esac

        unset empty

        cat <<-EOM
		${kind^^}

		${resource}

	EOM
    done

    if [ -v empty ]; then
        echo "No resources found."
    fi
}

main "${@}"; exit
