#!/bin/bash

set -eu
set -o pipefail


################################################################################

function error {
    echo "ERROR: ${*}" >/dev/stderr
}

function has-port {
    local port

    port="${1}"
    
    gdctl show | grep " ${port} " &>/dev/null
}

function probe-port {
    for i in 1 2 3 4 5 6; do
        for port in {HDMI,DP,DVI-I}-${i}; do
            if has-port "${port}"; then
                echo "${port}"
                return
            fi
        done
    done

    error "No recognized attached port!"
    return 2
}

function main {
    local screen

    screen="$(probe-port)"

    echo "Setting up ${screen} bottom left of eDP-1"

    # TODO: Expose direction and scaling as flags and env-vars
    gdctl set                                                                  \
          -L -M "${screen}" -p -s 1.0                                          \
          -L -M eDP-1 --left-of "${screen}" -y 1100 -s 1.0
}

main "${@}"; exit
