#!/bin/bash

set -eu
set -o pipefail


################################################################################

function error {
    echo "ERROR: ${*}" >/dev/stderr
}

function has-port {
    local port

    port="${1}"
    
    gdctl show | grep " ${port} " &>/dev/null
}

function probe-port {
    for port in HDMI-1 DP-1 DVI-I-1; do
        if has-port "${port}"; then
            echo "${port}"
            return
        fi
    done

    error "No recognized attached port!"
    return 2
}

function main {
    local screen port

    port="${1:-}"
    
    case "${port}" in
        displayLink|DVI|dvi) screen=DVI-I-1                                   ;;
        hdmi|HDMI)           screen=HDMI-1                                    ;;
        dp|DP|display-port)  screen=DP-1                                      ;;
        *)                   screen="$(probe-port)"                           ;;
    esac

    echo "Setting up ${screen} bottom left of eDP-1"

    # TODO: Expose direction and scaling as flags and env-vars
    gdctl set                                                                  \
          -L -M "${screen}" -p -s 1.0                                          \
          -L -M eDP-1 --left-of "${screen}" -y 1100 -s 1.0
}

main "${@}"; exit
