#!/bin/bash

set -eu
set -o pipefail


################################################################################

function error {
    echo "ERROR: ${*}" >/dev/stderr
}

function has-port {
    local port

    port="${1}"
    
    gdctl show | grep " ${port} " &>/dev/null
}

function probe-port {
    for port in HDMI-1 DP-1; do
        if has-port "${port}"; then
            echo "${port}"
            return
        fi
    done

    error "No recognized attached port!"
    return 2
}

function main {
    local screen port

    port="${1:-}"
    
    case "${port}" in
        hdmi|HDMI)          screen=HDMI-1          ;;
        dp|DP|display-port) screen=DP-1            ;;
        *)                  screen="$(probe-port)" ;;
    esac

    echo "Setting up ${screen} bottom left of eDP-1"

    gdctl set                                                                  \
          --logical-monitor --monitor "${screen}" --primary                    \
          --logical-monitor --monitor eDP-1       --left-of "${screen}" -y 1100
}

main "${@}"; exit
