#!/bin/bash

# Dynanic dispatch via task function
# shellcheck disable=SC2329

set -euo pipefail

BASE="${HOME}/Downloads/kernel"

################################################################################


function debug {
    if [ -v DEBUG ]; then
        echo "${FUNCNAME[1]:+${FUNCNAME[1]}: }${*}" >/dev/stderr
    fi
}

function error {
    echo "ERROR: ${*}" >/dev/stderr
}

function error-usage {
    error "${*}"
    echo
    usage
    return 2
}

function exists {
    local file

    for file in "${@}"; do
        debug "Check if '${file}' exists"
        test -f "${file}"
    done
}

function color {
    local color

    color="${1}"

    if ! maxcolors=$(tput colors 2>/dev/null) || [ "${maxcolors}" -lt 8 ]; then
        echo "${@:2}"
        return
    fi

    case "${color}" in
        b|black)   tput setaf 0 ;;
        r|red)     tput setaf 1 ;;
        g|green)   tput setaf 2 ;;
        y|yellow)  tput setaf 3 ;;
        u|blue)    tput setaf 4 ;;
        m|magenta) tput setaf 5 ;;
        c|cyan)    tput setaf 6 ;;
        w|white)   tput setaf 7 ;;
        *)         echo "ERROR: No such color ${color}!" >&2
                   return 2     ;;
    esac

    echo "${@:2}"

    tput sgr0
}

function task {
    local msg out
    local -a cmd

    msg="${1}"
    cmd=("${@:2}")

    printf "%-30s" "${msg} ... "

    if out="$("${cmd[@]}" 2>&1)"; then
        echo -e "[ $(color g -n ✓) ]"
    else
        echo -e "[ $(color r -n ×) ]"
        echo "${out}" | pr -to 6 >&2
        return 1
    fi
}

function os-version {
    # shellcheck source=/dev/null
    . /etc/os-release
    echo "${VERSION_ID}"
}

function sudo-ticket {
    local msg

    msg="${1}"

    if ! sudo -nv >/dev/null; then
        echo "${msg}"
        sudo -v
    fi
}

################################################################################

function ok-packages {
    local version fedora prefix suffix package

    version="${1}"

    prefix="${BASE}/${version}"
    suffix="${version}.fc$(os-version).x86_64.rpm"

    for package in kernel kernel-core kernel-modules kernel-modules-core; do
        echo "${prefix}/${package}-${suffix}"
    done
}

function ok-download {
    local dir package fedora

    dir="${1}"
    package="${2}"
    fedora="$(os-version)"

    pushd "${dir}" >/dev/null
    koji download-build                                                        \
         --arch=x86_64                                                         \
         --arch=noarch                                                         \
         "kernel-${package}.fc${fedora}"
    popd >/dev/null
}

function ok-list-download {
    local file fedora

    file="${1}"
    fedora="$(os-version)"

    koji list-builds                                                           \
         --prefix='kernel'                                                     \
         --state='COMPLETE'                                                    \
         --after="$(date --iso-8601 -d "1 year ago")"                          \
        | cut -d ' ' -f -1                                                     \
        | grep -E '^kernel-[0-9]+(\.[0-9]+){2}-[0-9]+.fc'"${fedora}"           \
        | sed -E 's/^kernel-(.+?).fc'"${fedora}"'$/\1/gi'                      \
              > "${file}"
}

function ok-list {
    local file

    file="${BASE}/fedora-$(os-version).list"

    if [ ! -f "${file}" ]; then
        ok-list-download "${file}"
    fi

    cat "${file}"
}

function ok-install {
    local dir version
    local -a versions=() packages=()

    dir="${1}"
    version="${2:-}"

    if [ -z "${version}" ]; then
        mapfile -t versions < <(ok-list); wait $!
        version="$(printf '%s\n' "${versions[@]}" | fzf)"
    fi

    dir="${BASE}/${version}"
    mkdir -p "${dir}"

    mapfile -t packages < <(ok-packages "${version}"); wait $!
    if ! exists "${packages[@]}" ; then
        echo
        echo "=== Download ${version} ==="
        echo
        ok-download "${dir}" "${version}" | pr -to 4
    fi

    echo
    echo "=== Install ${version} ==="
    echo
    sudo dnf install "${packages[@]}"

    echo
    echo "=== Installed kernels ==="
    echo
    dnf list kernel --showduplicates | pr -to 4
}

################################################################################

function usage {
    local name

    name=$(basename "${0}")

    cat <<EOM
Usage: ${name} list
       ${name} install [VERSION]

  -h, --help    Show this help message.

EOM
}

function main {
    local cmd dir

    if ! command -v koji &>/dev/null; then
        echo "Missing dependency 'koji'"
        return 2
    fi

    cmd="${1:-}"
    case "${cmd}" in
        installed) dnf list kernel --showduplicates                           ;;
        ls|list)   ok-list                                                    ;;
        install)   ok-install  "${1:-}"                                       ;;
        '')        error-usage "Missing command!"                             ;;
        *)         error-usage "Unknown command: ${cmd}"                      ;;
    esac

}

main "${@}"; exit
