#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-only
# Copyright 2022, Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>

# TODO:
#  - Clean up
#  - Fix state reporting
#
################################################################################

declare -a REPOS=(
    ~/Documents/Magic/decks/
    ~/.config/
    ~/.local/bin/
    ~/.config/emacs/
    ~/Code/github.com/mattiasb/MachineSetup/
)

declare -A COMMANDS=(
    # Just sync
    [~/Documents/Magic/decks/]=""
    [~/.config/]=""
    [~/.local/bin/]=""
    [~/Code/Test/]=""
    # Complex repositories
    [~/.config/emacs/]="systemctl --user restart emacs &"
    [~/Code/github.com/mattiasb/MachineSetup/]="./site.yml -vv -K"
)

declare -A STATE=(
    [neither]=0
    [pulled]=1
    [pushed]=2
    [both]=3
)

declare -A RECIPE=()

################################################################################

function red {
    echo " $(tput setaf 1)✗$(tput sgr0) ${*}"
}
function yellow {
    echo " $(tput setaf 3)✓$(tput sgr0) ${*}"
}
function green {
    echo " $(tput setaf 2)✓$(tput sgr0) ${*}"
}
function indent {
    echo "${*}" | pr -to 4
}

function confirm {
    read -p "${*} [Y/n] " -n 1 -r -s
    echo
    [[ $REPLY == "" || $REPLY =~ ^[Yy]$ ]]
}

function with-tilde {
    echo "${1/#$HOME/\~}"
}

################################################################################

function run-in-repo {
    local repo cmd

    repo="${1}"
    cmd="${2}"

    pushd "${repo}" >/dev/null
    eval "${cmd}"
    popd
}

function repo-in-sync {
    local repo head upstream

    repo="${1}"
    head="$(git -C "${repo}" rev-parse HEAD)"
    upstream="$(git -C "${repo}" rev-parse "@{u}")"

    test "${head}" = "${upstream}"
}

function sync {
    local repo rel state

    repo="${1}"
    # Relative Repo Path
    rel="${1/#$HOME/\~}"
    state=0

    if ! out="$(git -C "${repo}" status --short)"; then
        red "${rel} — Failed to check status"
        indent "${out}"
        return
    elif [ -n "${out}" ]; then
        red "${rel} — Dirty"
        return
    elif ! out="$(git -C "${repo}" fetch -q 2>&1)"; then
        red "${rel} — Failed to fetch"
        indent "${out}"
        return
    fi

    if ! repo-in-sync "${repo}"; then
        if ! out="$(git -C "${repo}" pull --rebase 2>&1)"; then
            red "${rel} — Failed to pull/rebase"
            indent "${out}"
            return
        fi

        state=$(( state + STATE[pulled] ))
        repo_tilde="$(with-tilde "${repo}")"
        if [ -n  "${COMMANDS[${repo_tilde}]}" ]; then
            RECIPE+=( [$repo]="${COMMANDS[${repo_tilde}]}" )
        fi
    fi

    if ! repo-in-sync "${repo}"; then
        if ! out="$(git -C "${repo}" push 2>&1)"; then
            red "${rel} — Failed to push"
            indent "${out}"
            return
        fi
        state=$(( state + STATE[pushed] ))
    fi

    case "$state" in
        "${STATE[neither]}") green "${rel}"
                             return ;;
        "${STATE[pulled]}")  yellow "${rel} — ↓"
                             return ;;
        "${STATE[pushed]}")  yellow "${rel} — ↑"
                             return ;;
        "${STATE[both]}")    yellow "${rel} — ↓↑"
                             return ;;
    esac
}

function parse-args {
    case "${#}" in
        0) return ;;
        1) case "${1}" in
               -h | --help)
                   usage "${@}"
                   exit 0
                   ;;
               -d | --debug)
                   set -x
                   return
                   ;;
               *) usage "${@}"
                  exit 2
                  ;;
           esac
           return
           ;;
        *) usage "${@}"
           exit 2
           ;;
    esac
}

function usage {
    echo "$(basename "${0}") [-h | -d]"
}

function main {
    local repo cmd

    parse-args "${@}"

    for repo in "${REPOS[@]}"; do
        sync "${repo}"
    done

    if [ "${#RECIPE[@]}" -gt 0 ]; then
        echo
    fi

    for repo in "${!RECIPE[@]}"; do
        cmd="${RECIPE[$repo]}"
        if confirm "$(with-tilde "${repo}") \$ ${cmd} ?"; then
            run-in-repo "${repo}" "${cmd}"
        fi
    done
}

################################################################################

set -e
set -o pipefail

main "$@" ; exit $?
