#!/bin/bash

# SPDX-License-Identifier: CC0-1.0
# Copyright 2016, Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>

set -e
set -o pipefail

################################################################################

function main {
    sudo dnf upgrade -y --offline
    echo
    sudo dnf offline reboot
}

main "${@}"; exit
