#!/bin/bash

# SPDX-License-Identifier: CC0-1.0
# Copyright 2016, Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>

pkcon refresh force           || exit $?
pkcon update --only-download  || exit $?
pkcon offline-trigger         || exit $?
