#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-only
# Copyright 2020, Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>

if ! [ -x /usr/bin/vagrant ]; then
    echo "Vagrant not installed!" >&2
    exit 2
fi

function idx {
    local str a
    str="${1}"
    shift
    a=( "${@}" )
    for i in $(seq 0 "${#}"); do
        if [ "${str}" = "${a[i]}" ]; then
            echo "$((i + 1))"
            return 0
        fi
    done

    return 1
}

a=( "${@}" )
if i="$(idx up "${@}")"; then
    a=( "${a[@]:0:$i}" "--no-destroy-on-error" "${a[@]:$i}" )
fi

exec /usr/bin/vagrant "${a[@]}"
