#!/bin/bash

set -e
set -o pipefail

VENV_BASEDIR="${XDG_DATA_HOME:-${HOME}/.local/share}/venv"
VENV_PYTHON="${VENV_PYTHON:-python}"

################################################################################

function error {
    echo "ERROR: ${*}" >&2
}

function confirm {
    local prompt reply

    prompt="${1}"

    read -r -n 1 -p "${prompt}? [Y/n] " reply
    if [ "$reply" != "" ]; then
        echo
    fi

    test "$reply" = "${reply#[Nn]}"
}

function usage {
    cat <<EOM
$(basename "${0}"): <COMMAND>

FLAGS

  --help    - Show this help

COMMANDS

  init      - Initialize a new venv
  activate  - Activate the venv
  remove    - Remove the virtual env
  status    - Check if the venv exists
  upgrade   - Upgrade core dependencies

ALIASES

  shell     - Same as "activate"
  rm        - Same as "remove"

EOM

}

function get-venv {
    case "${PWD}" in
        "${HOME}/"*)
            echo "${VENV_BASEDIR}/${PWD/${HOME}\//}"
            return 0
            ;;
        *)
            return 2
    esac
}

function venv {
    local flags

    flags=("${@}")

    ${VENV_PYTHON} -m venv "${flags[@]}" "$(get-venv)"
}

function pyvenv-config {
    echo "((python-mode . ((pyvenv-activate . \"$(get-venv)\"))))"
}

function ensure-venv {
    local venv

    venv="${1}"

    if [ ! -f "${venv}/bin/activate" ]; then
        error "Virtual env doesn't exist!"
        echo
        echo 'Create one with "venv init".'

        exit 3
    fi
}

function main {
    local cmd venv

    flags=("${@}")
    cmd="${1}"

    if ! venv="$(get-venv)"; then
        error "This tool only works within your HOME directory!"
        return 2
    fi

    case "${cmd}" in
        -h|--help)
            usage
            ;;

        init)
            if [ -f "${venv}/bin/activate" ]; then
                error "Virtual env already exists!"
                exit 3
            fi

            echo "Creating virtual env..."
            venv --upgrade-deps

            # TODO: Move this to emacs somehow
            echo "Writing Emacs pyvenv config"
            pyvenv-config > ./.dir-locals.el
            ;;

        activate|shell)
            ensure-venv "${venv}"

            # shellcheck source=/dev/null
            source "${venv}/bin/activate"
            exec /bin/bash -i
            ;;

        deactivate)
            ensure-venv "${venv}"

            # shellcheck source=/dev/null
            source "${venv}/bin/activate"
            exec /bin/bash -i
            ;;

        remove|rm)
            if [ ! -d "${venv}" ] || ! confirm "Remove venv"; then
                return
            fi

            echo "Removing venv ..."
            rm -rf "${venv}"

            # TODO: Move this to emacs somehow
            if [ -f ./.dir-locals.el ]; then
                rm  ./.dir-locals.el
            fi
            ;;

        status)
            if [ -f "${venv}/bin/activate" ]; then
                echo "A venv exists at:"
                echo
                echo "  ${venv/#$HOME/\~}"
                echo
            else
                echo 'No existing venv. Create one with "venv init".'
            fi
            ;;

        upgrade)
            ensure-venv "${venv}"

            echo "Upgrading venv ..."
            venv --upgrade-deps
            ;;
        
        *) error "No or unknown command!"
           echo
           usage
           return 2
           ;;
    esac
}

main "${@}"; exit
